### ISSUE TITLE
Incorrect info

### ISSUE THREAD

**Issue by bartolomej** [onflow/flip-fest#121]
Hey, I noticed that our team [`sheeeeeeeeesh`](https://www.hackerearth.com/challenges/hackathon/flip-fest/dashboard/d28305a/team/) wasn't included into submission results for issue "[Multiple contracts per account#21](https://github.com/onflow/flip-fest/blob/main/winners.md#playground-feature-multiple-contracts-per-account-21)", as we did achieve the first milestone here: https://github.com/onflow/flip-fest/pull/118#issuecomment-961499629.

## Correction
I think we should be listed in submission results with Total team payout of 250$ (for the first completed milestone).

**Comment by srinjoyc** [comment]
Hey @bartolomej thank you for the correction, we will include it. Is 100% of the reward going to you?

**Comment by srinjoyc** [comment]
Indeed, sorry for the error - I've included it now. Thanks!

**Comment by bartolomej** [comment]
Awesome, thanks!
