### ISSUE TITLE
Incorrect website link

### ISSUE THREAD

**Issue by bartolomej** [onflow/flip-fest#122]
Hey, I noticed that there are incorrect links in `winners.md` file for our `flippers` team, here: https://github.com/onflow/flip-fest/blob/main/winners.md#new-tool-block-explorer-gui-2.

- "Flowser Project Website" should be https://flowser.dev instead of https://bartolomej.github.io
- "Flowser repo" should be https://github.com/onflowser/flowser instead of https://github.com/bartolomej/flowser

Those were some older links, that should better be changed.

**Comment by srinjoyc** [comment]
Done! Thanks!
