### ISSUE TITLE
FCL Feature: Simplify `currentUser` syntax

### ISSUE THREAD

**Issue by srinjoyc** [onflow/flip-fest#25]
> 👋  &nbsp; If you are interested in working on this issue, please check out the [Getting Started guide on HackerEarth](https://www.hackerearth.com/challenges/hackathon/flip-fest/custom-tab/getting-started/#Getting%20Started)!

## Description (Problem Statement)

Simplify the syntax of the `fcl.currentUser` function into a class or object.

## Experience Required (Team Required)

- JS and familiarity with FCL `fcl.currentUser`

## Minimum Feature Set (Acceptance Criteria)

- Upon successful completion the following should be true:

```jsx
import {currentUser} from "@onflow/fcl"

// before
currentUser().subscribe(callback)
// after
currentUser.subscribe(callback)

// before
currentUser().snapshot()
// after
currentUser.snapshot()

// before
currentUser().authenticate
// after
currentUser.authenticate

// before
currentUser().authorization
// after
currentUser.authorization

// before
currentUser().asArg
// after
currentUser.asArg
```

## Milestone Requirements

- Update `fcl.currentUser()` from function to Class or Object syntax
- Add/Update tests
- Update Documentation - Add a description for this feature including sample code for usage in the existing API *[Docs](https://docs.onflow.org/fcl/api/)*

## Software Requirements

- Code should be written with best practices in mind.
- Other Requirements - Error Reporting
    - Throw descriptive exceptions on errors
    - Prints a clear error message to the browser console
- All core logic should have unit tests. Include tests for success on valid data and failure

## Other Requirements

- Updated Documentation describing the code, and usage

## Judging Criteria

- For all projects, [technical & high-level judging criteria apply](https://github.com/onflow/flip-fest/blob/main/resources/judging-criteria.md).

## Resources

- [Existing Issue](https://github.com/onflow/fcl-js/issues/709)

**Comment by gregsantos** [comment]
Hello folks! I'm Greg 👋🏼 😎  A Senior Javascript Developer on the DevEx Team.
If you choose this issue, I'll be your primary Point of Contact for any questions on implementation, code reviews, and/or help getting it over the finish line. Thanks for participating and Good Luck!
